### ISSUE TITLE
Why do we need this?

### ISSUE THREAD

**Issue by bkchr** [paritytech/scale-bits#1]

**Comment by jsdw** [comment]
One of the reasons I wrote this was to consolidate a bunch of bitvec encode and decode logic that's spread across a few crates (mainly related to decoding and encoding different shapes of bitvec based on scale-info type information, eg the `dynamic` stuff, or being able to easily skip over some bitvec bytes without decoding them at all). See https://docs.rs/scale-bits/latest/scale_bits/dynamic/struct.Format.html for some of this logic.

The other (opinionated reason) is that bitvec is pretty hideously overcomplicated, and if we just need some type to occasionally decode SCALE encoded bits into, we just don't need all of the unsafety and complexity in bitvec, and so this offers an alternative there.

**Comment by bkchr** [comment]
> The other (opinionated reason) is that bitvec is pretty hideously overcomplicated, and if we just need some type to occasionally decode SCALE encoded bits into, we just don't need all of the unsafety and complexity in bitvec, and so this offers an alternative there.

While I can not deny this. We (as parity) should not rewrite all the things. We can not take over writing all the things. Every crate we create brings some maintenance burden with it.

**Comment by jsdw** [comment]
I do agree and will be thinking about this more, but just to note that the amount of code here that overlaps specifically with bitvec is not that large (it could be swapped out for a bitvec even). 

Perhaps the most compelling reason for this is being able to decode from various different shapes of scale encoded bits (different store and order types) without either having to store an enum of different bitvecs or decode to a bitvec and then iterate it to transform it into a single canonical shape.

I think there is merit to having that logic (and was thinking about decoupling that a bit more from the concrete Bits type actually.. Eg being able to view some scale encoded bits as an iterator of bools for instance that could be streamed into whatever storage type you wanted to use).

Will have to think about this more though.

**Comment by jsdw** [comment]
@bkchr FYI I reflected on what you said, and reworked the crate and documentation; I'm a bunch happier with it now, so thanks for bringing this up!

The crate now clearly has two separate features; 

1. The useful dynamic decode/encode stuff (which will save a bunch of the same logic elsewhere, eg see https://github.com/paritytech/scale-decode/pull/5) and are alloc free and wasm compatible for all store/encodings (unlike bitvec's u64 store type as they feature flag it out on 32bit archs). With this, people can alloc-free stream bits into whatever container they like.
2. The opinionated `Bits` type; a simple implementation compatible with `BitVec<u8, Lsb0>`. I want to keep this type as I think that a) its much lower complexity/saves a few dependencies, and b) I think it's good to have more than one way to handle bit sequences anyway, and this also just acts as a demonstration that it's possible to use custom types in the first place. It's good imo that scale-info doesn't have to be opinionated now; it should just provide type information and leave the specifics up to the user.

I'll close this issue now, but happy to chat more about it if you like!
